export const FETCH_TEMPERATUREDATA = 'FETCH_TEMPERATUREDATA';
export const FETCH_PRESSUREDATA = 'FETCH_PRESSUREDATA';
export const FETCH_VIBRATIONDATA = 'FETCH_VIBRATIONDATA';
export const FETCH_CURRENTDATA = 'FETCH_CURRENTDATA';
export const FETCH_ULTRASOUNDDATA = 'FETCH_ULTRASOUNDDATA';